name: Go CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '*'
  release:
    types: [published]

jobs:
  setup:
    name: Test/Lint
    runs-on: ubuntu-latest
    outputs:
      workspace: ${{ steps.setup-path.outputs.workspace }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.0

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.61.0

      - name: Run go test
        run: go test -v ./...
          


